background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 16
    brightness = 0.6
}

label {
    monitor =
    text = cmd[update:3600] date "+%A, %-d de %B"
    color = rgba(ffffffcc)
    font_size = 24
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffff)
    font_size = 110
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, -50
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 54
    outline_thickness = 0

    outer_color = rgba(00000000)
    inner_color = rgba(0, 0, 0, 0.35)
    font_color = rgba(ffffffff)
    check_color = rgba(ffffffff)
    fail_color = rgba(ff4444aa)
    fail_text = Wrong Password
    placeholder_text = Password...
    hide_input = false
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false

    border_color = rgba(255, 255, 255, 0.12)
    border_width = 1
    rounding = 27

    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(ffffff99)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, -220
    halign = center
    valign = center
}
